apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8imn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-8imn@sha256:bd4d11c55e85496be38ab43b7a21604848d75c10362c852dfe0aa26a87a5de32
        name: my-nodejs
        resources: {}
status: {}
